string Lang[] = {
    "Escribe un numero entero positivo",
    "Tu número es menor que cero",
    "Tu número es perfecto",
    "Tu número no es perfecto",
    "Tu número no es primo",
    "Tu número es primo",
    "Escribe la posición",
    "Tu posición es invalida",
    "El número correspondiente es",
    "El rango maximo es de 100",
    "Escribe 0 si no desas usar switch",
    "Escribe un numero entero entre 1 y 7",
    "Bienvenido, Tu dia es",
    "Numero fuera de rango (1-7)",
    "Escribe tu nombre",
    "Bienvenido",
    "a nuestro sistema!",
    "Escribe tu edad",
    "Felicidades",
    "eres mayor de edad",
    "eres menor de edad",
    "Tu nombre es igual al del desarrollador"
};
